name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip

  tests:
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # other OS?
        python: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python ${{ matrix.python }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Run linting and tests with tox
        run: python -m tox run

      # Add coverage comment only if the Python env created the report
      - name: Pytest coverage comment
        if: ${{ hashFiles('coverage.xml') != '' }}
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ${{ github.workspace }}/coverage.xml
